# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CashManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'Drops', :git => 'https://github.com/omaralbeik/Drops.git', :tag => '1.6.0'
  pod 'lottie-ios'
  use_frameworks!

  # Pods for CashManager

  target 'CashManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CashManagerUITests' do
    # Pods for testing
  end

end
